import type { RiskLevel } from "@/features/finance/types";

export const trCopy = {
  app: {
    title: "Kişisel Finans Koçu",
    description: "TRY odaklı bütçe, borç kapatma ve finans koçu paneli.",
    brandKicker: "TRY koçu",
    brandName: "Finans kontrol paneli",
    mobileBrand: "Finans koçum",
    sidebarNote:
      "Bu sürüm test ve preview aşamasındadır. Auth ve kullanıcı bazlı veri izolasyonu tamamlanmadan gerçek finansal veriyle public kullanım için hazır değildir.",
  },
  nav: {
    dashboard: "Panel",
    income: "Gelir",
    debts: "Borçlar",
    expenses: "Giderler",
    plan: "Aylık plan",
    decisions: "Kararlar",
    forecast: "Tahmin",
    memory: "Hafıza",
    reminders: "Hatırlatmalar",
    mainAria: "Ana gezinme",
    mobileAria: "Mobil gezinme",
  },
  dashboard: {
    kicker: "Finans işletim sistemi",
    title: "Maaşını ayır, riskli ayları gör, borç kapatma planını netleştir.",
    intro:
      "Bu panel kayıtlı gelir, borç ve zorunlu gider bilgilerini kullanır. Bu sürüm Auth ve kullanıcı bazlı veri izolasyonu tamamlanmadan production veya public beta için hazır değildir.",
    monthlySalary: "Aylık maaş",
    monthlySalaryHelper: "Kayıtlı profilinizdeki güncel maaş.",
    mandatoryExpenses: "Zorunlu giderler",
    mandatoryExpensesHelper: "Kira, faturalar, temel gıda ve ulaşım.",
    minimumPayments: "Asgari ödemeler",
    minimumPaymentsHelper: "Aktif tüm borçların asgari ödemesi önce korunur.",
    survivalBudget: "Hayatta kalma bütçesi",
    survivalBudgetHelper: "Temel yükümlülüklerden sonra kalan tutar.",
    dailyLimit: "Günlük limit",
    dailyLimitHelper: "Ay sonuna kadar güvenli günlük harcama.",
    weeklyLimit: "Haftalık limit",
    weeklyLimitHelper: "Kalan günlere göre önerilen haftalık üst sınır.",
    riskTitle: "Bu ayın risk özeti",
    criticalReasons: "Kritik nedenler",
    warnings: "Uyarılar",
    noWarnings: "Bu ay için belirgin nakit akışı uyarısı yok.",
    salaryAllocation: "Maaş dağılımı",
    salaryAllocationHelper: "Gelir, zorunlu maliyetler, korunan tampon ve ek borç ödemesi.",
    debtPriority: "Borç öncelik sırası",
    debtPriorityHelper: "En yüksek aylık faiz oranına sahip borç önce hedeflenir.",
    payoffRoadmap: "Borç kapatma yol haritası",
    payoffRoadmapHelper: "Önümüzdeki 12 ay için kalan bakiye ve faiz projeksiyonu.",
  },
  charts: {
    income: "Gelir",
    expenses: "Giderler",
    minimums: "Asgariler",
    extraDebt: "Ek borç",
    buffer: "Tampon",
  },
  coach: {
    title: "Finans koçu",
    subtitle: "Koç güvenli AI modunda çalışır; canlı AI etkin değilse demo yorum gösterilir.",
    mode: "Güvenli mod",
    body:
      "Panel önce deterministik hesaplamaları kullanır. Canlı AI sağlayıcısı seçiliyse yalnız minimize edilmiş finans özeti gönderilebilir; ham finans kayıtları ve kişisel notlar gönderilmez.",
    actions: [
      "Zorunlu giderleri ve asgari ödemeleri önce güvenceye al.",
      "Hayatta kalma eşiği korunduktan sonra ek nakdi en yüksek aylık faizli karta yönlendir.",
      "TCMB oranlarını yasal azami bağlam olarak kullan; gerçek kart oranını ayrıca gir.",
    ],
    rateContext: "TCMB örnek bağlamı: aylık azami akdi faiz %{contractual}, aylık azami gecikme faizi %{overdue}.",
  },
  rates: {
    title: "TCMB faiz bağlamı",
    subtitle: "Türkiye kredi kartları için yasal azami faiz oranı referansı.",
    refresh: "Yenile",
    refreshing: "Yenileniyor",
    reference: "Referans",
    maxContractual: "Azami akdi",
    maxOverdue: "Azami gecikme",
    effective: "Geçerli dönem",
    retrieved: "Alınma zamanı",
    staleWarning:
      "Örnek veya önbellek benzeri veri kullanılıyor. Gerçek karta özel faiz oranını elle girin; TCMB oranları yasal azami bağlamdır.",
    sourceLink: "Resmi TCMB kaynağını aç",
    notAvailable: "Yok",
  },
  table: {
    rank: "Sıra",
    debt: "Borç",
    balance: "Bakiye",
    monthlyRate: "Aylık faiz",
    interestSource: "Faiz kaynağı",
    minimum: "Asgari",
    due: "Son ödeme",
    dueStatus: "Durum",
    recommendedPayment: "Önerilen ödeme",
    endingBalance: "Ödeme sonrası",
    day: "Gün",
  },
  dueStatus: {
    safe: "Güvenli",
    upcoming: "Yaklaşıyor",
    due_soon: "Riskli",
    due_today: "Bugün",
    overdue: "Gecikmiş",
    paid: "Ödendi",
  },
  forms: {
    incomeTitle: "Gelir ayarları",
    incomeDescription: "Gelir ve korunan bütçe eşiği kayıtlarını güncel finans planı için yönetin.",
    monthlySalary: "Aylık maaş",
    survivalThreshold: "Hayatta kalma bütçesi eşiği",
    preview: "Önizleme: maaş {salary}, korunan tampon {threshold}",
    debtsTitle: "Borçlar ve kartlar",
    debtsDescription: "Borç ve kart kayıtlarını aylık plan hesaplamaları için yönetin.",
    balance: "Bakiye",
    min: "Asgari",
    dueDay: "Son ödeme günü",
    totalSampleDebt: "Toplam örnek borç",
    expensesTitle: "Zorunlu giderler",
    expensesDescription: "Sabit aylık yükümlülük modelini şekillendirmek için bu sayfayı kullanın.",
    totalSampleExpenses: "Toplam örnek zorunlu gider",
  },
  plan: {
    title: "Aylık borç kapatma yol haritası",
    description: "Örnek borçlar, asgari ödemeler ve avalanche ek ödeme stratejisine dayalı 24 aylık deterministik projeksiyon.",
    extraPayoff: "Ek ödeme",
    survivalBudget: "Hayatta kalma bütçesi",
    risk: "Risk",
    remainingDebt: "Kalan borç",
    actionPlan: "Bu ayın aksiyon planı",
    paymentPlan: "Bu ay önerilen ödemeler",
    interest: "Faiz",
    totalPayment: "Toplam ödeme",
  },
  decisions: {
    title: "Karar Simülatörü",
    description:
      "Gerçek kayıtlarınızı değiştirmeden, seçtiğiniz kararın mevcut aylık plan ve borç kapanış yol haritası üzerindeki etkisini görün.",
    caveat:
      "Bu ekran deterministik finans motoruyla karar desteği sağlar. Sonuçlar kesin finansal tavsiye, yatırım tavsiyesi, hukuki görüş veya banka kararı değildir.",
  },
  forecast: {
    kicker: "Forecast Engine",
    title: "Finansal Tahmin",
    description:
      "Mevcut gelir, gider, borç, faiz ve ödeme planına göre 3, 6, 12 ve 24 aylık deterministik projeksiyon. Bu ekran tahmin sağlar; kesin finansal tavsiye değildir.",
    setupTitle: "Tahmin için eksik bilgiler var",
    setupDescription:
      "Anlamlı bir finansal tahmin için gelir, zorunlu gider ve en az bir aktif borç kaydı gerekir. Gelecek görünümü demo veri kullanmadan kayıtlı finans bilgilerini okur.",
    finalRemainingDebt: "24 ay sonu kalan borç",
    estimatedPayoffMonth: "Tahmini kapanış ayı",
    totalInterest: "Toplam tahmini faiz",
    highestRisk: "En riskli seviye",
    outsideHorizon: "24 ay dışında",
    checkpointTitle: "Tahmin dönemleri",
    debtTrend: "Kalan borç trendi",
    livingBudgetTrend: "Yaşam bütçesi trendi",
    riskTrend: "Risk trendi",
    cashSqueeze: "Nakit sıkışıklığı uyarıları",
    payoffMilestones: "Borç kapanış kilometre taşları",
    assumptions: "Forecast varsayımları",
    coachTitle: "Türkçe koç yorumu",
    noWarnings: "24 aylık pencerede belirgin nakit sıkışıklığı uyarısı yok.",
    noMilestones: "24 aylık pencerede kapanması beklenen borç görünmüyor.",
    noActiveDebt: "Aktif borç olmadığı için borç trendi üretilemiyor.",
  },
  memory: {
    kicker: "Financial Memory",
    title: "Finansal Hafıza",
    description:
      "Bu analiz kayıtlı finansal hafıza snapshot’larına dayanır. Financial Memory kendi başına OpenAI veya Gemini çağrısı yapmaz; koç katmanı yalnız minimize edilmiş özetleri kullanabilir.",
    refresh: "Hafızayı güncelle",
    emptyTitle: "Henüz finansal hafıza yok",
    emptyDescription:
      "Gelir, gider ve borç kayıtlarınızdan aylık bir snapshot oluşturduğunuzda sistem trendleri ve alışkanlık içgörülerini izlemeye başlar.",
    notEnoughHistoryTitle: "Yeterli geçmiş yok",
    notEnoughHistoryDescription:
      "Trend ve davranış analizi için en az iki aylık finansal hafıza gerekir. Şimdilik güncel durum snapshot’ı saklanıyor.",
    comparisons: "3 / 6 / 12 ay karşılaştırmaları",
    debtTrend: "Borç trendi",
    budgetTrend: "Yaşam bütçesi ve gider trendi",
    insights: "Deterministik koç içgörüleri",
    categoryChanges: "Kategori değişimleri",
    triggers: {
      manual_refresh: "Manuel güncelleme",
      income_changed: "Gelir değişti",
      salary_record_changed: "Maaş geçmişi değişti",
      debt_changed: "Borç değişti",
      expense_changed: "Gider değişti",
    },
  },
  risk: {
    low: "Düşük",
    medium: "Orta",
    high: "Yüksek",
    critical: "Yüksek",
  } satisfies Record<RiskLevel, string>,
  api: {
    coachError: "Koç içgörüsü üretilemedi.",
  },
};
